<a href="https://colab.research.google.com/github/eduardocarbo/NewRepo/blob/master/PLATZI_NUMPY_Introducci%C3%B3n_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INTRODUCCIÓN CON NUMPY

In [4]:
!pip install numpy

In [5]:
import numpy as np


In [6]:
#CREAMOS UN ARRAY PARA EL EJERCICIO:
np.array([10,20,24,5,15,50]) #como es un métdo lo metemos en corchetes cuadrados

array([10, 20, 24,  5, 15, 50])

In [7]:
a = np.array([10,30,20,4,30,512,7,2,4,40,100]) # los arreglos comienzan desde cero en adelante
a[4]#esta es la posición 4

30

In [8]:
#mostrar los datos del arreglo a partir de otra posición
a[3:] #en este caso se imprimime desde la posición 3 en adelante

array([  4,  30, 512,   7,   2,   4,  40, 100])

In [9]:
a[3:7] #arreglo por intervalos

array([  4,  30, 512,   7])

In [10]:
#imprimir el arreglo cada 4 espacios
a[1::4]

array([ 30, 512,  40])

In [11]:
#PODEMOS CREAR ARREGLOS DE UNA FORMA DINÁMICA:
np.zeros(5) # es un método y está alimentado por un parámetro que es 5

array([0., 0., 0., 0., 0.])

In [12]:
np.ones((4,5))#arregl ode 2 dimensiones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
#si queremos llenar el array con otros valores
type.ones

AttributeError: ignored

In [24]:
#SI QUEREMOS SABER QUE TIP ODE DATO ES UNO DE ESTOS VALORES.
type(ones[3])

NameError: ignored

In [25]:
#ara hacer pruebas para graficas o demás:
np.linspace(3, 10,5) # el 3 es el nivel inferior, 10 es el nivel superior y 5 el número de elementos

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [26]:
#Podemos crear arreglos de 2 dimensiones y lso separamos por medio de corchetes
b = np.array([['x','y','z'],['a','c','e',]])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [27]:
#para saber las dimensiones que tiene
b.ndim # dice que tiene 2 dimensiones

2

In [28]:
#vamos a crear un nuevo array para otro ejercicio
#función muy util ára el ordenamiento de datos
c = [12,4,10,40,2]
#y ahora lo vamos ordenando de MENOR a MAYOR
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [21]:
#POR QUE MEDIOS QUEREMOS ORGANIZAR EL ARREGLO
cabeceras = [('nombre','S10'),('edad',int)]
datos = [('Juan',10),('Maria',70),('Javier',42),('Samuel',15)]
usuarios = np.array(datos, dtype = cabeceras)
np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [29]:
#tenemos la opci´no de llenarlos de una manera dinámica los arreglos
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
np.arange(5,30) # generamos los números con limite inferior y el superior

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
np.arange(5,50,5) #menor 5 , mayor50 , cada 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
#Arreglo de tipo bidimensional:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [33]:
# la siguiente la vamos a utilizar con matrices:
np.diag([0,3,9,10]) # es para indicarle a numpy que queremos una diagonal con esos números

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [20]:
#arreglo de 3 dimesniones y organizarlos por edad, por nombre y por pais
#Arreglo de 3 dimesniones con NUMPY:
np.zeros((3,5,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [18]:
#Otra forma de hacer la matriz en 3 dimensiones:
np.ones(((3,5,6)))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [40]:
#Hacemos un array con edad, nombre y país
cabeceras = [('nombre','S10'),('edad',int),('pais','S10')]
datos = [('Juan',10,'Canada'),('Maria',70,'Colombia'),('Javier',42,'Venezuela'),('Samuel',15,'EEUU')]
usuarios = np.array(datos, dtype = cabeceras)
np.sort(usuarios, order = 'edad')

array([(b'Juan', 10, b'Canada'), (b'Samuel', 15, b'EEUU'),
       (b'Javier', 42, b'Venezuela'), (b'Maria', 70, b'Colombia')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S10')])